name: deploy-boilerbooks
on:
  push:
    branches:
      master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Deploy Boiler Books"
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_github
          chmod 600 ~/.ssh/id_github
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ~/.ssh/id_github "echo GH actions working > test.txt"
          rm ~/.ssh/id_github
